name: Build Wheels (CPU) (MacOS)

on: workflow_dispatch

permissions:
  contents: write

jobs:

  build_wheels_macos:
    name: Build wheels on macos-${{ matrix.os }}
    runs-on: macos-${{ matrix.os }}
    strategy:
      matrix:
        os: [12, 13, 14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          # disable repair
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_BUILD_FRONTEND: "build"
          CIBW_ENVIRONMENT: CMAKE_ARGS="-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64"
          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*"
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.os }}
          CMAKE_BUILD_PARALLEL_LEVEL: 4
        with:
          package-dir: .
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  release:
    name: Release
    needs: [build_wheels_macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
